services:
  - type: web
    name: load-tube
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: '4000'
      - key: TEMP_DIR
        value: /app/temp
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: CORS_ORIGIN
        sync: false
      - key: GMAIL_USER
        sync: false
      - key: GMAIL_APP_PASSWORD
        sync: false
